### ISSUE TITLE
Code available

### ISSUE THREAD

**Issue by vamWu** [endogslam/EndoGSLAM#1]
Really outstanding work!!!
Hi, I would like to ask you when the code will be open? I would really want to learn more about the work you have done

**Comment by Loping151** [comment]
Sorry for the late reply. I was preparing for final exams at that time.

The code is released now. Thank you for being interested.

**Comment by vamWu** [comment]
Thanks for the reply, I have seen the code.

Loping151 ***@***.***> 于2024年6月23日周日 19:27写道：
