### ISSUE TITLE
Question about the processed depth images

### ISSUE THREAD

**Issue by jdeng21** [endogslam/EndoGSLAM#10]
Hi, author. I really appreciate your work. I noticed you set the depth scale to 2.55 in config file. But in the original C3VD dataset, values of the depth images are from 65535 to 0. Could you please explain how you process the depth images? Thank you very much! @Loping151

**Comment by Loping151** [comment]
According my note, I scaled the depth image: x/65535*255 during preprosess. According to the C3VD page, the scale for 0-65535 equals 0-100mm. So the scale 2.55 is to convert the processed depth scale back to original.

**Comment by jdeng21** [comment]
Thank you very much for your quick response! Appreciate it!
