### ISSUE TITLE
Question in "eval_save" during training

### ISSUE THREAD

**Issue by jywu511** [endogslam/EndoGSLAM#7]
Thanks for publishing the good work! 
When I reproduced the training code, I emcompassed following error in "eval_save" function. Can you provide some suggestions about this error？
Thanks very much.

Best regards

![image](https://github.com/user-attachments/assets/076fa4e0-be9c-4566-9074-7d0b016a85b0)

**Comment by jywu511** [comment]
surprisingly, I find that when I closed the tmux, this bug could be fixed.

**Comment by Loping151** [comment]
I'm so sorry for the very late reply. Somehow I failed to receive emails for this repo.
To me this seems a problem of package version. If...if you still have the problem, plz provide more info and I'll see if I can still help.

**Comment by jywu511** [comment]
Thanks very much for your reply. This issue is solved. The issue is due to my computer.
