### ISSUE TITLE
Question regarding the keyframes and the length of gt_train_w2c

### ISSUE THREAD

**Issue by bsticker** [endogslam/EndoGSLAM#9]
It looks like the poses of the keyfiles are not saved. If I change the `keyframe_every` to a different number, it does not give any other result either. Do you have a suggestion how I can see these keyfiles? 
Also I do not understand why the `gt_train_w2c` is not the same length as the groundtruth file (`pose.txt`) but shorter. It is the same length as `est_w2c.txt`. How do I change the length of the file and what makes the `est_w2c.txt` shorter than the number of depth/color images it was given? In the `eval_save` function the num_frames is defined by the length of the dataset, but this makes me think that it should be as long as the total amount of color/depth images there are (and thus the length of the ground truth `pose.txt` file).

**Comment by Loping151** [comment]
I'm so sorry for the very late reply. Somehow I failed to receive emails for this repo.

What do you mean keyfiles? For the poses, all the poses for train indices should be saved in `est_w2c`. 

About the length: there is a train-test split used when evaluating the nvs quality:
utils/eval_helpers.py
```python
            if (total_time_idx + 1) % 8 != 0:
                dataset_type = 'train'
                _dataset = train_dataset
                time_idx = total_time_idx - (total_time_idx // 8)
            else:
                dataset_type = 'test'
                _dataset = eval_dataset
                time_idx = total_time_idx//8
```
7 of every 8 frames are feed into endogslam, and the gt_train_w2c is the corresponding poses on the training indices for evaluation. It is only for evaluating the traj, ensuring the indices are the same as est_w2c.
